### ISSUE TITLE
ConnectionError: Error occurred during handling the request: failed to connect to all addresses

### ISSUE THREAD

**Issue by kmanisai** [openvinotoolkit/model_server#1366]
I am getting this error when i was running demos which uses ovmsclient, Is this issue with the proxy or any other.
Help me resolve this,

CMD : sudo docker run --rm --network=host -it -u $(id -u):$(id -g) -e GRPC_PORT=9001 -v $(pwd)/results:/results face_blurdemo:latest

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ovmsclient/tfs_compat/grpc/serving_client.py", line 47, in predict
    raw_response = self.prediction_service_stub.Predict(request.raw_request, timeout)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1661469649.468043906","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1661469649.468043550","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "face_blur.py", line 73, in <module>
    raise err
  File "face_blur.py", line 71, in <module>
    response = client.predict(input, args['pipeline_name'])
  File "/usr/local/lib/python3.8/site-packages/ovmsclient/tfs_compat/grpc/serving_client.py", line 49, in predict
    raise_from_grpc(grpc_error)
  File "/usr/local/lib/python3.8/site-packages/ovmsclient/tfs_compat/base/errors.py", line 66, in raise_from_grpc
    raise(error_class(details))
ConnectionError: Error occurred during handling the request: failed to connect to all addresses

**Comment by mzegla** [comment]
Please check if your model server starts okay and make sure you forward the ports that it uses. 
If from model server side everything is fine, then maybe it's a proxy issue. I can see that you have a demo client inside a docker container. Maybe adding `localhost` to `no_proxy` ENV in the container would help?
