### ISSUE TITLE
OVMS Docker & Python gRPC Client - Hostname works, IP does not

### ISSUE THREAD

**Issue by tkalceca** [openvinotoolkit/model_server#1655]
Hi OVMS Team,

I'm using OVMS Docker container *OpenVINO Model Server 2022.3*, i.e. from `docker pull openvino/model_server:latest`. Starting container works actually fine. However, if doing some testing from client side, like described here: https://github.com/openvinotoolkit/model_server/blob/6385a43554589686179def48430c140f42b19c8d/client/python/ovmsclient/lib/docs/grpc_client.md, i.e.:

(Using python virtualenv with this [requirements.txt](https://github.com/openvinotoolkit/model_server/blob/6385a43554589686179def48430c140f42b19c8d/demos/real_time_stream_analysis/python/requirements.txt))
```python
import ovmsclient
client = ovmsclient.make_grpc_client("localhost:9000")
# request metadata of the specific model version, with timeout set to 2.5 seconds
model_metadata = client.get_model_metadata(model_name="model", model_version=1, timeout=2.5)
```

* On local side only *localhost:9000* works, but *127.0.0.1:9000* does not
* On external device only *hostname.domain.com:9000* works, but *10.62.xx.yy:9000* does not

On latter receiving:
```
Traceback (most recent call last):
  File "openvino/model_server/venv/lib/python3.8/site-packages/ovmsclient/tfs_compat/grpc/serving_client.py", line 63, in get_model_metadata
    raw_response = self.prediction_service_stub.GetModelMetadata(request.raw_request,
  File "openvino/model_server/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "openvino/model_server/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1673368091.464465682","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "grpc_test.py", line 4, in <module>
    model_metadata = client.get_model_metadata(model_name="heart-rate", model_version=1, timeout=2.5)
  File "openvino/model_server/venv/lib/python3.8/site-packages/ovmsclient/tfs_compat/grpc/serving_client.py", line 66, in get_model_metadata
    raise_from_grpc(grpc_error)
  File "openvino/model_server/venv/lib/python3.8/site-packages/ovmsclient/tfs_compat/base/errors.py", line 66, in raise_from_grpc
    raise (error_class(details))
TimeoutError: Error occurred during handling the request: Request handling exceeded timeout
```

Any clue?

**Comment by mzegla** [comment]
Hi Andrej,

I guess that when you hit localhost or a domain, you don't go through proxy and while targeting IPs directly, the requests go to the proxy server first. Could you try adding desired IPs to `no_proxy` environment variable and try again?

**Comment by tkalceca** [comment]
Hi Milosz,

I have 10.0.0.0/8 in my `$no_proxy` per default, so, not sure if it's really proxy related. Furthermore if running locally, it accepts `localhost`, but not `127.0.0.1`, same pattern?! If switching the test to `make_http_client(`, actually it works both ways, domain and IP. Basically I run the app this way `python real_time_stream_analysis.py --stream_url rtsp://<IP>:8554/mystream --ovms_url <domain>:9000 --model_name heart-rate --log_level ERROR --buffer_size 300 --inference_executors 1` to work, i.e. <IP> and <domain> are the same destination. However, only for gRCP (`--ovms_url`) version I have to specify the domain.

Anyway, it works with domain, so if this issue is not of high importance (or still can be issue on my infrastructure side, or even gRPC only accepts domains and not IPs), feel free to close this ticket.

Thanks, Andrej

**Comment by mzegla** [comment]
It looked like a proxy issue at the first glance, so I'd make sure that proxy is not the issue 100%. Putting exact IP to $no_proxy, trying to connect to the IP with other tool in verbose mode to see if the traffic is really going directly to the right place etc. 

So when you use http client instead of grpc it works both with domains and IPs? In the exactly same setting like for gRPC?  
That's strange and in such case I'd probably look into firewall settings maybe. But since you have a working solution you may not want to invest time in investigating this, so if there's no activity in this thread I'll close it in a day or two.
