### ISSUE TITLE
Error in image classification example - Missing input with specific name - Required input: Func/StatefulPartitionedCall/input/_0:0

### ISSUE THREAD

**Issue by NeethuES-intel** [openvinotoolkit/model_server#1769]
I am getting the following error while running the image_classification example 
 python image_classification.py --grpc_port 9001 --input_name 0 --output_name 0 --images_list ../input_images.txt
2023-03-28 23:50:42.866553: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-28 23:50:43.001053: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-28 23:50:43.001082: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-28 23:50:43.619789: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-28 23:50:43.619861: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-28 23:50:43.619875: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Start processing:
	Model name: resnet
	Images list file: ../input_images.txt
../../common/static/images/airliner.jpeg (1, 3, 224, 224) ; data range: 0.0 : 255.0
Traceback (most recent call last):
  File "image_classification.py", line 98, in <module>
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
  File "/home/nesubuntu207/miniconda3/envs/bentoml_env/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/nesubuntu207/miniconda3/envs/bentoml_env/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Missing input with specific name - Required input: Func/StatefulPartitionedCall/input/_0:0"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:9001 {created_time:"2023-03-28T23:50:44.465119114-07:00", grpc_status:3, grpc_message:"Missing input with specific name - Required input: Func/StatefulPartitionedCall/input/_0:0"}"

Following is the metadata of the model -
resnet via http: {'inputs': {'Func/StatefulPartitionedCall/input/_0:0': {'dtype': 'DT_FLOAT', 'shape': [1, 60, 60, 1]}}, 'outputs': {'Func/StatefulPartitionedCall/output/_52:0': {'dtype': 'DT_FLOAT', 'shape': [1, 1]}}, 'model_version': 1}

Based on this I changed input_name to 0 & output_name to 0, but getting this missing input with specific name error. Can someone please help.

**Comment by mzegla** [comment]
Looking at the server response and model metadata, the input and output name would be:
`--input_name Func/StatefulPartitionedCall/input/_0:0 --output_name Func/StatefulPartitionedCall/output/_52:0` 

but note that this sample works with standard ResNet model and looking at your model input and output it doesn't look like it (in this sample we run pre and post processing assuming certain input and output shapes, while you have different ones)

**Comment by NeethuES-intel** [comment]
Thanks you. Changing the model worked with the same parameters 0 for input_data & 1463 for output_data
