### ISSUE TITLE
Grpc server cannot work

### ISSUE THREAD

**Issue by yingwei13mei** [openvinotoolkit/model_server#1923]
When I followed https://github.com/openvinotoolkit/model_server/tree/develop/client/python/kserve-api/samples, and have executed docker run with "docker run --rm -v $(pwd)/models:/models -p 9000:9000 -p 8000:8000 openvino/model_server:latest --model_name resnet --model_path /models/resnet --port 9000 --rest_port 8000 --layout NHWC:NCHW" 
The result seems ok as following:

> [2023-06-20 03:02:59.097][1][serving][info][server.cpp:76] OpenVINO Model Server 2023.0.c0bee9c6
> [2023-06-20 03:02:59.097][1][serving][info][server.cpp:77] OpenVINO backend 2023.0.0.10926.b4452d56304
> [2023-06-20 03:02:59.113][1][modelmanager][info][modelmanager.cpp:121] Available devices for Open VINO: CPU, GNA
> [2023-06-20 03:02:59.115][1][serving][info][grpcservermodule.cpp:116] GRPCServerModule starting
> [2023-06-20 03:02:59.116][1][serving][info][grpcservermodule.cpp:168] GRPCServerModule started
> [2023-06-20 03:02:59.116][1][serving][info][grpcservermodule.cpp:169] Started gRPC server on port 9000
> [2023-06-20 03:02:59.116][1][serving][info][httpservermodule.cpp:33] HTTPServerModule starting
> [2023-06-20 03:02:59.116][1][serving][info][httpservermodule.cpp:37] Will start 32 REST workers
> [2023-06-20 03:02:59.118][1][serving][info][http_server.cpp:257] REST server listening on port 8000 with 32 threads
> [evhttp_server.cc : 251] NET_LOG: Entering the event loop ...
> [2023-06-20 03:02:59.118][1][serving][info][httpservermodule.cpp:47] HTTPServerModule started
> [2023-06-20 03:02:59.118][1][serving][info][httpservermodule.cpp:48] Started REST server at 0.0.0.0:8000
> [2023-06-20 03:02:59.118][1][serving][info][servablemanagermodule.cpp:40] ServableManagerModule starting
> [2023-06-20 03:02:59.118][1][serving][info][model.cpp:41] Getting model from /models/resnet
> [2023-06-20 03:02:59.118][1][serving][info][model.cpp:48] Model downloaded to /models/resnet
> [2023-06-20 03:02:59.118][1][serving][info][model.cpp:148] Will add model: resnet; version: 1 ...
> [2023-06-20 03:02:59.118][1][serving][info][modelversionstatus.cpp:109] STATUS CHANGE: Version 1 of model resnet status change. New status: ( "state": "START", "error_code": "OK" )
> [2023-06-20 03:02:59.118][1][serving][info][modelinstance.cpp:898] Loading model: resnet, version: 1, from path: /models/resnet/1, with target device: CPU ...
> [2023-06-20 03:02:59.118][1][serving][info][modelversionstatus.cpp:109] STATUS CHANGE: Version 1 of model resnet status change. New status: ( "state": "START", "error_code": "OK" )
> [2023-06-20 03:02:59.118][1][serving][info][modelversionstatus.cpp:109] STATUS CHANGE: Version 1 of model resnet status change. New status: ( "state": "LOADING", "error_code": "OK" )
> [2023-06-20 03:02:59.158][1][modelmanager][info][modelinstance.cpp:443] Input name: 0; mapping_name: 0; shape: (1,224,224,3); precision: FP32; layout: NHWC
> [2023-06-20 03:02:59.158][1][modelmanager][info][modelinstance.cpp:491] Output name: 1463; mapping_name: 1463; shape: (1,1000); precision: FP32; layout: N...
> [2023-06-20 03:02:59.671][1][modelmanager][info][modelinstance.cpp:1282] Number of OpenVINO streams: 8
> [2023-06-20 03:02:59.671][1][modelmanager][info][modelinstance.cpp:705] Plugin config for device: CPU
> [2023-06-20 03:02:59.671][1][modelmanager][info][modelinstance.cpp:709] OVMS set plugin settings key: PERFORMANCE_HINT; value: LATENCY;
> [2023-06-20 03:02:59.676][1][serving][info][modelinstance.cpp:793] Loaded model resnet; version: 1; batch size: 1; No of InferRequests: 8
> [2023-06-20 03:02:59.676][1][serving][info][modelversionstatus.cpp:109] STATUS CHANGE: Version 1 of model resnet status change. New status: ( "state": "AVAILABLE", "error_code": "OK" )
> [2023-06-20 03:02:59.676][1][serving][info][model.cpp:88] Updating default version for model: resnet, from: 0
> [2023-06-20 03:02:59.676][1][serving][info][model.cpp:98] Updated default version for model: resnet, to: 1
> [2023-06-20 03:02:59.676][1][serving][info][servablemanagermodule.cpp:44] ServableManagerModule started
> [2023-06-20 03:02:59.676][124][modelmanager][info][modelmanager.cpp:1103] Started cleaner thread
> [2023-06-20 03:02:59.676][123][modelmanager][info][modelmanager.cpp:1085] Started model manager thread

But when I try this "python3 ./grpc_server_live.py --grpc_port 9000 --grpc_address localhost", it came out:

> Traceback (most recent call last):
>   File "./grpc_server_live.py", line 35, in <module>
>     response = grpc_stub.ServerLive(request)
>   File "/.../.../kserve-api/samples/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 1030, in __call__
>     return _end_unary_response_blocking(state, call, False, None)
>   File "/.../.../kserve-api/samples/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
>     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> 	status = StatusCode.UNAVAILABLE
> 	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:10.239.120.56:911: Socket closed"
> 	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:10.239.120.56:911: Socket closed {grpc_status:14, created_time:"2023-06-20T03:04:11.881438129+00:00"}"
> >

And if I try "python3 ./http_server_live.py --http_port 8000 --http_address localhost", the result is ok, and the inference by http server is also OK.

So, does the GRPC server have some difference usage or something wrong, for there's no error message when starting the docker container?

**Comment by yingwei13mei** [comment]
close local proxy, could resolve it
