### ISSUE TITLE
Incompatibility with TensorFlow Serving RPC Interface

### ISSUE THREAD

**Issue by kuaikuai** [openvinotoolkit/model_server#2582]
Title: Incompatibility with TensorFlow Serving RPC Interface
Description:
I am experiencing compatibility issues when attempting to use the OpenVINO Model Server with the TensorFlow Serving RPC interface. When I send requests to the OpenVINO Model Server using the same format as TensorFlow Serving, I receive unexpected responses or errors that suggest incompatibilities between the two systems.

Environment:
OpenVINO Model Server Version: 2024.2
TensorFlow Serving Version: 2.14.0
Python Version: 3.11

Started the OpenVINO Model Server with a savedmodel file.

Send Request Using TensorFlow Serving Client:
Sent a request to the OpenVINO Model Server using the TensorFlow Serving client with the following Python code:
`
import grpc
import numpy as np
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc
from grpc.beta import implementations
import tensorflow as tf

server = 'x.x.x.x:8500' 
model_name = 'my_model'
model_version = '1'

# Construct the request
request = predict_pb2.PredictRequest()
request.model_spec.name = model_name
request.model_spec.version.value = int(model_version)
request.model_spec.signature_name = 'serving_default'

request.inputs['item.actors_key'].CopyFrom(tf.make_tensor_proto(np.array([[50473,12863,0,0,0,0,0,0,0,0]]), dtype=np.int32))
request.inputs['item.actors_value'].CopyFrom(tf.make_tensor_proto(np.array([[0.9,0.81,0,0,0,0,0,0,0,0]]), dtype=np.float32))
request.inputs['item.click'].CopyFrom(tf.make_tensor_proto(np.array([[0]]), dtype=np.int32))

channel = grpc.insecure_channel(server)
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

response = stub.Predict(request, 5.0) 

# Print the response
print(response)
`
Error:
Traceback (most recent call last):
  File "/data/test.py", line 204, in <module>
    response = stub.Predict(request, 5.0)  # 5.0 is the timeout in seconds
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid content size of tensor proto - Expected: 4 bytes; Actual: 0 bytes; input name: item.click"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Invalid content size of tensor proto - Expected: 4 bytes; Actual: 0 bytes; input name: item.click", grpc_status:3, created_time:"2024-07-26T11:01:11.77534443+00:00"}"

**Comment by kuaikuai** [comment]
even a very simple model
`#+begin_src python
import tensorflow as tf
import numpy as np

# Generate some random data for demonstration
np.random.seed(0)
items = np.random.rand(100, 1)
out = 2 * items + 1 + 0.1 * np.random.randn(100, 1)

# Define the simple linear regression model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1])
])

model.compile(optimizer='sgd', loss='mean_squared_error')

# Train the model
model.fit(items, out, epochs=100)

# Export the model as a SavedModel
export_dir = 'saved_model'
tf.saved_model.save(model, export_dir)
#+end_src`

use ovc to covert the saved_model file, and load by ovms.

restful API is good.
curl -d '{"instances": [ [1.0] ] }' -X POST http://localhost:8501/v1/models/saved_model:predict
{
    "predictions": [[3.06347656]
    ]
}

grpc api doesn't work.
test.py:
`
import grpc
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc
from grpc.beta import implementations
import tensorflow as tf
server = '127.0.0.1:8500'
model_name = 'saved_model'
model_version = '1'
request = predict_pb2.PredictRequest()
request.model_spec.name = model_name
request.model_spec.version.value = int(model_version)
request.model_spec.signature_name = 'serving_default' 

channel = grpc.insecure_channel(server)
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

request.inputs['dense_input'].CopyFrom(tf.make_tensor_proto(np.array([[1.0]]), dtype=np.float32))
response = stub.Predict(request, 5.0)
print(response)
`
Error:
Invalid content size of tensor proto - Expected: 4 bytes; Actual: 0 bytes; input name: dense_input

**Comment by bstrzele** [comment]
Hi @kuaikuai,

Tensorflow's `make_tensor_proto`, when the input array has only one value, returns partial request that is currently unsupported, i.e.:
```python
>>> tf.make_tensor_proto(np.array([[0]]), dtype=np.int32)
dtype: DT_INT32
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 1
  }
}
int_val: 0
```
as opposed to
```python
>>> tf.make_tensor_proto(np.array([[0, 1]]), dtype=np.int32)
dtype: DT_INT32
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
tensor_content: "\000\000\000\000\001\000\000\000"
```
OVMS only parses input values located in tensor_content, and support for other value fields is not planned at the moment.
For gRPC any solution compliant with [Kserve API](https://docs.openvino.ai/2024/ovms_docs_clients_kfs.html) would not face this issue and it is the prefered method of communication with Model Server.

**Comment by kuaikuai** [comment]
why does OVMS only parse input values located in tensor_content?  Is parsing tensor_content faster than other value fields?

**Comment by bstrzele** [comment]
This representation is type agnostic and reduces serialization overhead during RPC call by avoiding serialization of many repeated small items. Type specific representation (e.g. int_val) is slightly less performant and redundant.
