### ISSUE TITLE
can not export bge-reranker-base in windows

### ISSUE THREAD

**Issue by TatvaJoshi** [openvinotoolkit/model_server#2924]
(.venv) PS D:\Projects\model_server\demos\common\export_models> python export_model.py rerank --source_model BAAI/bge-reranker-base --weight-format int8  --config_file_path models/config_all.json
template params: {'task': 'rerank', 'target_device': 'CPU', 'num_streams': '1', 'max_doc_length': 16000}
Exporting rerank model to  models\BAAI/bge-reranker-base\rerank\1
config.json: 100%|█████████████████████████████████████████████████████████████████| 799/799 [00:00<00:00, 266kB/s]
d:\projects\.venv\lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\tatvajoshi\.cache\huggingface\hub\models--BAAI--bge-reranker-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
model.safetensors: 100%|███████████████████████████████████████████████████████| 1.11G/1.11G [00:08<00:00, 133MB/s]
tokenizer_config.json: 100%|███████████████████████████████████████████████████████| 443/443 [00:00<00:00, 111kB/s]
sentencepiece.bpe.model: 100%|████████████████████████████████████████████████| 5.07M/5.07M [00:00<00:00, 98.9MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████| 17.1M/17.1M [00:00<00:00, 97.7MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████| 279/279 [00:00<00:00, 69.7kB/s]
Traceback (most recent call last):
  File "C:\Users\tatvajoshi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tatvajoshi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Projects\.venv\Scripts\optimum-cli.exe\__main__.py", line 7, in <module>
  File "d:\projects\.venv\lib\site-packages\optimum\commands\optimum_cli.py", line 208, in main
    service.run()
  File "d:\projects\.venv\lib\site-packages\optimum\commands\export\openvino.py", line 397, in run
    main_export(
  File "d:\projects\.venv\lib\site-packages\optimum\exporters\openvino\__main__.py", line 445, in main_export
    submodel = core.read_model(submodel_path)
  File "d:\projects\.venv\lib\site-packages\openvino\runtime\ie_api.py", line 502, in read_model
    return Model(super().read_model(model))
RuntimeError: Exception from src\inference\src\cpp\core.cpp:90:
Exception from src\frontends\ir\src\ir_deserializer.cpp:355:
Incorrect weights in bin file!

Traceback (most recent call last):
  File "D:\Projects\model_server\demos\common\export_models\export_model.py", line 376, in <module>
    export_rerank_model(args['model_repository_path'], args['source_model'], args['model_name'] ,args['precision'], template_parameters, str(args['version']), args['config_file_path'], args['max_doc_length'])
  File "D:\Projects\model_server\demos\common\export_models\export_model.py", line 331, in export_rerank_model      
    raise ValueError("Failed to export rerank model", source_model)
ValueError: ('Failed to export rerank model', 'BAAI/bge-reranker-base')

**Comment by dtrawins** [comment]
@TatvaJoshi  there were added a couple of updates in the export tool on the main branch. There was set a specific version of the Openvino and the tokenizer dependencies and there was also one correction specific to the script execution on windows.
Can you retry using the version from main and the requirements also from main branch? 
Also make sure there is sufficient disk space on your host.

**Comment by TatvaJoshi** [comment]
@dtrawins the export file works perfectly. Thx for quick resolution. 

However, I am trying to deploy the exported model in the model server docker image. I created the docker image and container through this command:
docker run -d --rm -p 8000:8000 -p 9000:9000 -v "C:\models:/workspace:ro" openvino/model_server:latest --port 9000 --rest_port 8000 --config_path /workspace/config.json

Upon successful creation container, in the logs of it, I am seeing these errors that. Please help me how to fix it.

"2024-12-23 10:40:44 [2024-12-23 17:40:44.899][1][serving][info][servablemanagermodule.cpp:51] ServableManagerModule starting
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][info][modelmanager.cpp:554] Configuration file doesn't have custom node libraries property.
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][info][modelmanager.cpp:597] Configuration file doesn't have pipelines property.
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][error][mediapipegraphdefinition.cpp:73] Failed to open mediapipe graph definition: BAAI/bge-reranker-base, file: /workspace/BAAI\bge-reranker-base/graph.pbtxt
2024-12-23 10:40:44 
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][info][pipelinedefinitionstatus.hpp:59] Mediapipe: BAAI/bge-reranker-base state changed to: LOADING_PRECONDITION_FAILED after handling: ValidationFailedEvent:"

Logs:

2024-12-23 10:40:44 [2024-12-23 17:40:44.810][1][serving][info][server.cpp:84] OpenVINO Model Server 2024.5.816f620b6
2024-12-23 10:40:44 [2024-12-23 17:40:44.810][1][serving][info][server.cpp:85] OpenVINO backend 2024.5.0.17288.7975fa5da0c
2024-12-23 10:40:44 [2024-12-23 17:40:44.810][1][serving][info][pythoninterpretermodule.cpp:35] PythonInterpreterModule starting
2024-12-23 10:40:44 [2024-12-23 17:40:44.879][1][serving][info][pythoninterpretermodule.cpp:46] PythonInterpreterModule started
2024-12-23 10:40:44 [2024-12-23 17:40:44.880][1][serving][info][modelmanager.cpp:128] Loading tokenizer CPU extension from libopenvino_tokenizers.so
2024-12-23 10:40:44 [2024-12-23 17:40:44.893][1][modelmanager][info][modelmanager.cpp:143] Available devices for Open VINO: CPU
2024-12-23 10:40:44 [2024-12-23 17:40:44.893][1][serving][info][grpcservermodule.cpp:163] GRPCServerModule starting
2024-12-23 10:40:44 [2024-12-23 17:40:44.894][1][serving][info][grpcservermodule.cpp:232] GRPCServerModule started
2024-12-23 10:40:44 [2024-12-23 17:40:44.894][1][serving][info][grpcservermodule.cpp:233] Started gRPC server on port 9000
2024-12-23 10:40:44 [2024-12-23 17:40:44.894][1][serving][info][httpservermodule.cpp:33] HTTPServerModule starting
2024-12-23 10:40:44 [2024-12-23 17:40:44.894][1][serving][info][httpservermodule.cpp:37] Will start 48 REST workers
2024-12-23 10:40:44 [2024-12-23 17:40:44.899][1][serving][info][http_server.cpp:276] REST server listening on port 8000 with 48 threads
2024-12-23 10:40:44 [2024-12-23 17:40:44.899][1][serving][info][httpservermodule.cpp:47] HTTPServerModule started
2024-12-23 10:40:44 [2024-12-23 17:40:44.899][1][serving][info][httpservermodule.cpp:48] Started REST server at 0.0.0.0:8000
2024-12-23 10:40:44 [2024-12-23 17:40:44.899][1][serving][info][servablemanagermodule.cpp:51] ServableManagerModule starting
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][info][modelmanager.cpp:554] Configuration file doesn't have custom node libraries property.
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][info][modelmanager.cpp:597] Configuration file doesn't have pipelines property.
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][error][mediapipegraphdefinition.cpp:73] Failed to open mediapipe graph definition: BAAI/bge-reranker-base, file: /workspace/BAAI\bge-reranker-base/graph.pbtxt
2024-12-23 10:40:44 
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][modelmanager][info][pipelinedefinitionstatus.hpp:59] Mediapipe: BAAI/bge-reranker-base state changed to: LOADING_PRECONDITION_FAILED after handling: ValidationFailedEvent: 
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][100][modelmanager][info][modelmanager.cpp:1097] Started model manager thread
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][1][serving][info][servablemanagermodule.cpp:55] ServableManagerModule started
2024-12-23 10:40:44 [2024-12-23 17:40:44.902][101][modelmanager][info][modelmanager.cpp:1116] Started cleaner thread
2024-12-23 10:40:44 [evhttp_server.cc : 253] NET_LOG: Entering the event loop ...

**Comment by TatvaJoshi** [comment]
Additional info: this is the reponse it gives when trying to hit the api:
C:\Users\tatvajoshi>curl.exe "http://localhost:8000/v3/rerank" -H "Content-Type: application/json" -d "{ \"model\": \"BAAI/bge-reranker-base\", \"query\": \"welcome\", \"documents\":[\"good morning\",\"farewell\"]}" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137  100    40  100    97   1379   3345 --:--:-- --:--:-- --:--:--  4892
{
  "error": "Mediapipe is not loaded yet"
}

**Comment by TatvaJoshi** [comment]
Solved the issue. It was a silly mistake. I had to change the path in config.json from window's to linux format. for those who are having this issue, change the config.json to this:

{
    "mediapipe_config_list": [
        {
            "name": "BAAI/bge-reranker-base",
            "base_path": "BAAI/bge-reranker-base"
        }
    ],
    "model_config_list": []
}

from 

{
    "mediapipe_config_list": [
        {
            "name": "BAAI/bge-reranker-base",
            "base_path": "BAAI\\bge-reranker-base"
        }
    ],
    "model_config_list": []
}
