### ISSUE TITLE
!Error:Failed to pick subchannel

### ISSUE THREAD

**Issue by pengguanjun** [openvinotoolkit/model_server#313]
I can't find the reason.Seek help,thanks.

**NOTE:**
[root@VM-0-15-centos ~]# `python3 get_serving_meta.py --grpc_port 9000 --model_name semantic-segmentation-adas --model_version 1`
2020-10-18 23:21:10.053573: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-18 23:21:10.053619: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Getting model metadata for model: semantic-segmentation-adas
Traceback (most recent call last):
  File "get_serving_meta.py", line 97, in <module>
    result = stub.GetModelMetadata(request, 10.0) # result includes a dictionary with all model outputs
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 690, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 592, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1603034471.856134639","description":"**Failed to pick subchannel**","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3934,"referenced_errors":[{"created":"@1603034471.856132122","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"

**Comment by pengguanjun** [comment]
![图片](https://user-images.githubusercontent.com/29192658/96372583-103cfc00-119a-11eb-8fee-2891043e8fde.png)

**Comment by dtrawins** [comment]
@pengguanjun This error indicate connectivity problems. The client can not connect the the server endpoint. It might be several root causes:
- ovms is not started or is using different port (check the ovms server logs)
- ovms is started on external IP - the default `grpc_address` in the client is localhost
- port is not exposed in docker container via `-p` parameter
- proxy settings are preventing direct access to the target IP

**Comment by pengguanjun** [comment]
@dtrawins
thanks, you get the key point.
I have changed the port 9000 to port 9001 before.
I need to check the ovms server logs.But I can not find the proper code for a long time.

Could you give me the specific code to check the ovms server logs?
Best wish to you, thanks a lot.

As following,there ara my check process.
NOTE:
[root@VM-0-15-centos ~]# `docker run -v /root/models/model2/1:/models/model2/1:ro -p 9000:9000 openvino/model_server:latest --model_path /models/model2 --model_name semantic-segmentation-adas --port 9000 --log_level DEBUG --shape auto`
[2020-10-20 14:20:24.903] [serving] [debug] CLI parameters passed to ovms server
[2020-10-20 14:20:24.903] [serving] [debug] model_path: /models/model2
[2020-10-20 14:20:24.903] [serving] [debug] model_name: semantic-segmentation-adas
[2020-10-20 14:20:24.903] [serving] [debug] batch_size: 0
[2020-10-20 14:20:24.903] [serving] [debug] shape: auto
[2020-10-20 14:20:24.903] [serving] [debug] model_version_policy: 
[2020-10-20 14:20:24.903] [serving] [debug] nireq: 0
[2020-10-20 14:20:24.903] [serving] [debug] target_device: CPU
[2020-10-20 14:20:24.903] [serving] [debug] plugin_config: 
[2020-10-20 14:20:24.903] [serving] [debug] gRPC port: 9000
[2020-10-20 14:20:24.903] [serving] [debug] REST port: 0
[2020-10-20 14:20:24.903] [serving] [debug] REST workers: 24
[2020-10-20 14:20:24.903] [serving] [debug] gRPC workers: 1
[2020-10-20 14:20:24.903] [serving] [debug] gRPC channel arguments: 
[2020-10-20 14:20:24.903] [serving] [debug] log level: DEBUG
[2020-10-20 14:20:24.903] [serving] [debug] log path: 
[2020-10-20 14:20:24.903] [serving] [debug] Batch size set: false, shape set: true
[2020-10-20 14:20:24.903] [serving] [debug] Currently registered versions count:0
[2020-10-20 14:20:24.903] [serving] [info] Getting model from /models/model2
[2020-10-20 14:20:24.903] [serving] [info] Model downloaded to /models/model2
[2020-10-20 14:20:24.903] [serving] [info] Will add model: semantic-segmentation-adas; version: 1 ...
[2020-10-20 14:20:24.903] [serving] [info] Loading model: semantic-segmentation-adas, version: 1, from path: /models/model2/1, with target device: CPU ...
[2020-10-20 14:20:24.903] [serving] [info] Some inputs shapes for model semantic-segmentation-adas are set to auto
[2020-10-20 14:20:24.903] [serving] [info] STATUS CHANGE: Version 1 of model semantic-segmentation-adas status change. New status: ( "state": "START", "error_code": "OK" )
[2020-10-20 14:20:24.903] [serving] [debug] setLoading: semantic-segmentation-adas - 1 (previous state: START) -> error: OK
[2020-10-20 14:20:24.903] [serving] [info] STATUS CHANGE: Version 1 of model semantic-segmentation-adas status change. New status: ( "state": "LOADING", "error_code": "OK" )
[2020-10-20 14:20:24.903] [serving] [debug] Getting model files from path:/models/model2/1
[2020-10-20 14:20:24.904] [serving] [debug] Try reading model file:/models/model2/1/semantic-segmentation-adas-0001.xml
[2020-10-20 14:20:25.074] [serving] [debug] Network shape - (1,3,1024,2048); Final shape - (1,3,1024,2048)
[2020-10-20 14:20:25.074] [serving] [info] Input name: data; mapping_name: ; shape: 1 3 1024 2048 ; precision: FP32, layout:NCHW
[2020-10-20 14:20:25.074] [serving] [debug] model: semantic-segmentation-adas, version: 1; reshaping inputs is not required
[2020-10-20 14:20:25.074] [serving] [info] Output name: 4455.1 ; mapping name: ; shape: 1 1 1024 2048  ; precision: I32, layout:NCHW
[2020-10-20 14:20:26.019] [serving] [info] Plugin config for device CPU:
[2020-10-20 14:20:26.019] [serving] [info] CPU_THROUGHPUT_STREAMS: CPU_THROUGHPUT_AUTO
[2020-10-20 14:20:26.019] [serving] [info] Loaded model semantic-segmentation-adas; version: 1; batch size: 1; No of InferRequests: 1
[2020-10-20 14:20:26.019] [serving] [debug] setAvailable: semantic-segmentation-adas - 1 (previous state: LOADING) -> error: OK
[2020-10-20 14:20:26.019] [serving] [info] STATUS CHANGE: Version 1 of model semantic-segmentation-adas status change. New status: ( "state": "AVAILABLE", "error_code": "OK" )
[2020-10-20 14:20:26.019] [serving] [info] Updating default version for model:semantic-segmentation-adas, from:0
[2020-10-20 14:20:26.019] [serving] [info] [model.cpp:47] Updated default version for model:semantic-segmentation-adas, to:1
[2020-10-20 14:20:26.019] [serving] [debug] Starting grpc servers: 1
[2020-10-20 14:20:26.020] [serving] [info] Server started on port 9000
[2020-10-20 14:20:26.020] [serving] [info] [modelmanager.cpp:297] Started config watcher thread
[2020-10-20 14:20:27.022] [serving] [debug] Currently registered versions count:1
[2020-10-20 14:20:27.022] [serving] [debug] version:1 state:AVAILABLE
[2020-10-20 14:20:28.023] [serving] [debug] Currently registered versions count:1
[2020-10-20 14:20:28.023] [serving] [debug] version:1 state:AVAILABLE
[2020-10-20 14:20:29.024] [serving] [debug] Currently registered versions count:1
[2020-10-20 14:20:29.024] [serving] [debug] version:1 state:AVAILABLE
[2020-10-20 14:20:30.026] [serving] [debug] Currently registered versions count:1
[2020-10-20 14:20:30.026] [serving] [debug] version:1 state:AVAILABLE
[2020-10-20 14:20:31.027] [serving] [debug] Currently registered versions count:1
[2020-10-20 14:20:31.027] [serving] [debug] version:1 state:AVAILABLE
^C[2020-10-20 14:20:32.021] [serving] [info] Shutting down
[2020-10-20 14:20:32.028] [serving] [debug] Currently registered versions count:1
[2020-10-20 14:20:32.028] [serving] [debug] version:1 state:AVAILABLE
[2020-10-20 14:20:32.028] [serving] [info] Exited config watcher thread
[root@VM-0-15-centos ~]# docker psCONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@VM-0-15-centos ~]# tree
.
|-- get_serving_meta.py
|-- images
|   `-- scene1.jpg
|-- models
|   |-- model1
|   |   `-- 1
|   `-- model2
|       |-- 1
|       |   |-- semantic-segmentation-adas-0001.bin
|       |   `-- semantic-segmentation-adas-0001.xml
|       `-- 2
|-- results
`-- sky_detection.py

8 directories, 5 files

![图片](https://user-images.githubusercontent.com/29192658/96600523-99336f00-1323-11eb-8748-2539a0aca042.png)

[root@VM-0-15-centos ~]# `python3  sky_detection.py --batch_size 1 --width 600 --height 400 --input_images_dir images --output_dir results **--log**`
2020-10-20 22:33:30.707394: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-20 22:33:30.707457: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
usage: sky_detection.py [-h] [--input_images_dir INPUT_IMAGES_DIR]
                        [--output_dir OUTPUT_DIR] [--batch_size BATCH_SIZE]
                        [--width WIDTH] [--height HEIGHT]
                        [--grpc_address GRPC_ADDRESS] [--grpc_port GRPC_PORT]
**sky_detection.py: error: unrecognized arguments: --log**

**Comment by dtrawins** [comment]
@pengguanjun the logs your included above indicates that ovms started successfully on port 9000 with model semantic-segmentation-adas. You should be able to connect with `python get_model_meta.py --grpc_port 9000 --model_name semantic-segmentation-adas`. That script shows the model metadata.
I suppose the script sky_detection.py is based on face_detection.py example from the repo. It doesn't have `--logs` parameter.

**Comment by dtrawins** [comment]
@pengguanjun Is it resolved now?

**Comment by pengguanjun** [comment]
@dtrawins 
Thanks,I get it.

I just add `-d` ,it works.
`docker run -v /root/models/model2/1:/models/model2/1:ro -p 9000:9000 openvino/model_server:latest --model_path /models/model2 --model_name semantic-segmentation-adas --port 9000 --log_level DEBUG --shape auto`

`docker run `-d` -v /root/models/model2/1:/models/model2/1:ro -p 9000:9000 openvino/model_server:latest --model_path /models/model2 --model_name semantic-segmentation-adas --port 9000 --log_level DEBUG --shape auto`

I follow this way to try.
The linker:
[](https://www.cnblogs.com/jsxyhelu/p/13829051.html?tdsourcetag=s_pctim_aiomsg)

![图片](https://user-images.githubusercontent.com/29192658/97576159-c28d8280-1a28-11eb-9d43-d7f8c9d1fb1e.png)

![图片](https://user-images.githubusercontent.com/29192658/97575968-80fcd780-1a28-11eb-82ce-a19bac21daf3.png)

**Comment by rasapala** [comment]
Issue resolved.
