### ISSUE TITLE
Given config is invalid according to schema: #/definitions/model_config/properties/config. Keyword: additionalProperties Key: #/model_config_list/0/config/layout

### ISSUE THREAD

**Issue by ParthM-GitHub** [openvinotoolkit/model_server#755]
I am using the latest [config.json](https://raw.githubusercontent.com/openvinotoolkit/model_server/main/src/custom_nodes/model_zoo_intel_object_detection/config_vehicles_example.json) file.

When I try to start the container, I am getting the following error:

```
[********@********** new_workspace_ovms]$ sudo docker logs b29df855fbaab776db6369de57d534cf7e636483ad2337d1b1e10e255c7d4abb
[2021-07-05 12:42:10.545][1][serving][info][server.cpp:105] OpenVINO Model Server 2021.3.c9ba5cfa
[2021-07-05 12:42:10.545][1][serving][info][server.cpp:106] OpenVINO backend 2021.3.394
[2021-07-05 12:42:10.545][1][serving][error][schema.cpp:333] Given config is invalid according to schema: #/definitions/model_config/properties/config. Keyword: additionalProperties Key: #/model_config_list/0/config/layout
[2021-07-05 12:42:10.545][1][modelmanager][error][modelmanager.cpp:533] Configuration file is not in valid configuration format
[2021-07-05 12:42:10.545][1][modelmanager][error][modelmanager.cpp:73] Couldn't start model manager
[2021-07-05 12:42:10.545][1][serving][error][server.cpp:186] ovms::ModelManager::Start() Error: The file is not valid json
```

Any help would be appreciated, Thanks.

**Comment by bhargav-sudo** [comment]
I am also facing the same issue.

Help needed.

Thanks.

**Comment by mzegla** [comment]
From the logs I can see that you're using version 2021.3. 
This config you linked contains `layout` parameter that was not available in previous versions. 
Can you update your model server to 2021.4 and see if that helps?

**Comment by bhargav-sudo** [comment]
Hi @mzegla 

I am facing this error while using Analysis of multiple vehicles in single image frame request in OVMS

[2021-07-06 07:04:30.254][serving][error][schema.cpp:273] Given config is invalid according to schema: #/definitions/model_config/properties/config. Keyword: additionalProperties Key: #/model_config_list/0/config/layout
[2021-07-06 07:04:30.254][modelmanager][error][modelmanager.cpp:400] Configuration file is not in valid configuration format
[2021-07-06 07:04:30.254][modelmanager][error][modelmanager.cpp:60] Couldn't start model manager
[2021-07-06 07:04:30.254][serving][error][server.cpp:175] ovms::ModelManager::Start() Error: The file is not valid json


Command in docker : 

 **docker run -p 9000:9000 -v ${PWD}/workspace:/workspace openvino/model_server --config_path /workspace/config.json --port 9000**

Help needed.

Thanks.

**Comment by mzegla** [comment]
@bhargav-sudo We had a release a few days ago. Are you sure you're using the latest OVMS image?
At the main branch some config files may contain parameters introduced in the 2021.4 release so I recommend using the latest version if possible.

**Comment by bhargav-sudo** [comment]
ok will check with that and let you know.

Thaks.

**Comment by bhargav-sudo** [comment]
Hi @mzegla 
I think it says here I am using the old version.
![Screenshot from 2021-07-06 14-05-10](https://user-images.githubusercontent.com/57169077/124569188-5a1e5d00-de63-11eb-844e-bbc891f2d6ed.png)

How can I update that to latest version.


Thanks.

**Comment by mzegla** [comment]
Running `docker pull openvino/model_server` should do the job

**Comment by bhargav-sudo** [comment]
Will do that and let you know ..

Thanks.

**Comment by bhargav-sudo** [comment]
Hi @mzegla 

I tried like you said.

Command : **docker pull openvino/model_server** 
It works fine.

Using default tag: latest
latest: Pulling from openvino/model_server
Digest: sha256:faa9f7f8cd68c1250ab288ee4478f1fcd36eee5c63d122ca8bce401363a5dd6b
Status: Image is up to date for openvino/model_server:latest
docker.io/openvino/model_server:latest


After this I tried to build the openvino model server.
command : **make docker_build**
 It throws error like this

![Screenshot from 2021-07-06 19-19-02](https://user-images.githubusercontent.com/57169077/124611563-307b2b00-de8f-11eb-9527-25ac8214ac72.png)


I hope you would know something about this error.

Thanks.

**Comment by mzegla** [comment]
Once you pull the image, you don't have to build it with `make docker_build`.
Run the docker container just like before with `docker run`  and `openvino/model_server:latest` as the image name. 

About this error. How fresh is your repository? Could you provide SHA of the commit that you run `make docker_build` on? 
Did you pull main branch recently and run it there?

**Comment by bhargav-sudo** [comment]
Hi @mzegla 

I just run the docker image 
command : docker run -p 9000:9000 -v ${PWD}/workspace:/workspace openvino/model_server --config_path /model_server/example_client/workspace/config.json --port 9000

It throws error like this : 

[2021-07-06 14:10:41.416][1][serving][info][server.cpp:105] OpenVINO Model Server 2021.4.b0af59c9
[2021-07-06 14:10:41.423][1][serving][info][server.cpp:106] OpenVINO backend 2021.4.582
[2021-07-06 14:10:41.423][1][modelmanager][error][modelmanager.cpp:543] Configuration file is invalid /model_server/example_client/workspace/config.json
[2021-07-06 14:10:41.423][1][modelmanager][error][modelmanager.cpp:73] Couldn't start model manager
[2021-07-06 14:10:41.423][1][serving][error][server.cpp:186] ovms::ModelManager::Start() Error: Configuration file not found or cannot open

Thanks.

**Comment by mzegla** [comment]
It looks like the path to your configuration file is wrong. In the `--config_path` parameter you should specify the path to `config.json` **in the container**. So looking at your mount and the command you tried to run I'd assume that the valid path to config would be `/workspace/config.json`. Try going with:
`docker run -p 9000:9000 -v ${PWD}/workspace:/workspace openvino/model_server --config_path /workspace/config.json --port 9000`
Also keep in mind that OVMS needs models files to work so they should be present under paths set in config.json.

**Comment by bhargav-sudo** [comment]
@mzegla 
 
It runs successfully.
But when I run python file 
It says error like this.

command : **python3 vehicles_analysis_pipeline_client.py --pipeline_name multiple_vehicle_recognition --grpc_port 9000 --image_input_path ./images/cars/road1.jpg --vehicle_images_output_name vehicle_images --vehicle_images_save_path ./results --image_width 512 --image_height 512 --input_image_layout NHWC**

Error : 
**vehicles_analysis_pipeline_client.py: error: unrecognized arguments: --input_image_layout NHWC**

Thanks.

**Comment by mzegla** [comment]
You most likely run on some old commit. Please make sure you use up-to-date **main** branch or **v2021.4** tag. 
Simply checkout to one of this branches and pull the changes if possible.

**Comment by bhargav-sudo** [comment]
Ok will check and let you know.

**Comment by bhargav-sudo** [comment]
@mzegla 

I used v2021.4 tag
Server has started.

And it throws new error.

**command** : python3 vehicles_analysis_pipeline_client.py --pipeline_name multiple_vehicle_recognition --grpc_port 9000 --image_input_path ./images/cars/road1.jpg --vehicle_images_output_name vehicle_images --vehicle_images_save_path ./results --image_width 512 --image_height 512 --input_image_layout NHWC


**Error** :  
2021-07-06 20:21:07.642561: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-06 20:21:07.642584: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "vehicles_analysis_pipeline_client.py", line 124, in <module>
    raise err
  File "vehicles_analysis_pipeline_client.py", line 118, in <module>
    response = stub.Predict(request, 30.0)
  File "/.local/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/.local/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Pipeline is not loaded yet"
	debug_error_string = "{"created":"@1625583068.591789701","description":"Error received from peer ipv6:[::1]:9000","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Pipeline is not loaded yet","grpc_status":5}"

**Comment by bhargav-sudo** [comment]
Hi @mzegla 

It works now.

Thanks for the assistance.
You helped me a lot.

Thanks.
