### ISSUE TITLE
camera_example.md does not work 

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/model_server#776]
https://github.com/openvinotoolkit/model_server/blob/CVS-59920_text_detection/docs/camera_example.md

Here is what I see when starting the OVMS container: 
```
[2021-07-15 20:32:40.921][1][serving][info][server.cpp:105] OpenVINO Model Server 2021.4.b0af59c9

[2021-07-15 20:32:40.926][1][serving][info][server.cpp:106] OpenVINO backend 2021.4.582

[2021-07-15 20:32:40.933][1][serving][info][model.cpp:38] Getting model from /model

[2021-07-15 20:32:40.933][1][serving][info][model.cpp:45] Model downloaded to /model

[2021-07-15 20:32:40.933][1][serving][info][model.cpp:145] Will add model: horizontal-text-detection; version: 1 ...

[2021-07-15 20:32:40.938][1][serving][info][modelinstance.cpp:526] Loading model: horizontal-text-detection, version: 1, from path: /model/1, with target device: CPU ...

[2021-07-15 20:32:40.938][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model horizontal-text-detection status change. New status: ( "state": "START", "error_code": "OK" )

[2021-07-15 20:32:40.938][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model horizontal-text-detection status change. New status: ( "state": "LOADING", "error_code": "OK" )

[2021-07-15 20:32:41.256][1][serving][info][modelinstance.cpp:160] Final network inputs:

Input name: image; mapping_name: ; shape: (1,3,704,704); effective shape: (1,704,704,3); precision: FP32; layout: NHWC

[2021-07-15 20:32:41.256][1][serving][info][modelinstance.cpp:195] Output name: 1078_1079.0; mapping name: ; shape: 1000 ; effective shape 1000 ; precision: FP32; layout: C

[2021-07-15 20:32:41.256][1][serving][info][modelinstance.cpp:195] Output name: 1141_1142.0; mapping name: ; shape: 1000 ; effective shape 1000 ; precision: FP32; layout: C

[2021-07-15 20:32:41.257][1][serving][info][modelinstance.cpp:195] Output name: 1204_1205.0; mapping name: ; shape: 484 ; effective shape 484 ; precision: FP32; layout: C

[2021-07-15 20:32:41.257][1][serving][info][modelinstance.cpp:195] Output name: 1267_1268.0; mapping name: ; shape: 121 ; effective shape 121 ; precision: FP32; layout: C

[2021-07-15 20:32:41.257][1][serving][info][modelinstance.cpp:195] Output name: 1330_1331.0; mapping name: ; shape: 36 ; effective shape 36 ; precision: FP32; layout: C

[2021-07-15 20:32:41.257][1][serving][info][modelinstance.cpp:195] Output name: 1469_1470.0; mapping name: ; shape: 100 ; effective shape 100 ; precision: FP32; layout: C

[2021-07-15 20:32:41.257][1][serving][info][modelinstance.cpp:195] Output name: boxes; mapping name: ; shape: 100 5 ; effective shape 100 5 ; precision: FP32; layout: NC

[2021-07-15 20:32:41.257][1][serving][info][modelinstance.cpp:195] Output name: labels; mapping name: ; shape: 100 ; effective shape 100 ; precision: I32; layout: C

[2021-07-15 20:32:42.041][1][serving][info][modelinstance.cpp:397] Plugin config for device CPU:

[2021-07-15 20:32:42.041][1][serving][info][modelinstance.cpp:401] CPU_THROUGHPUT_STREAMS: CPU_THROUGHPUT_AUTO

[2021-07-15 20:32:42.042][1][serving][info][modelinstance.cpp:456] Loaded model horizontal-text-detection; version: 1; batch size: 1; No of InferRequests: 1

[2021-07-15 20:32:42.042][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model horizontal-text-detection status change. New status: ( "state": "AVAILABLE", "error_code": "OK" )

[2021-07-15 20:32:42.042][1][serving][info][model.cpp:85] Updating default version for model: horizontal-text-detection, from: 0

[2021-07-15 20:32:42.043][1][serving][info][model.cpp:95] Updated default version for model: horizontal-text-detection, to: 1

[2021-07-15 20:32:42.043][52][modelmanager][info][global_sequences_viewer.cpp:76] Started sequence cleaner thread

[2021-07-15 20:32:42.043][51][modelmanager][info][modelmanager.cpp:662] Started model manager thread

[2021-07-15 20:32:42.049][1][serving][info][server.cpp:226] Server started on port 9001

[2021-07-15 20:35:20.499][57][dag_executor][info][pipeline_factory.cpp:84] Pipeline with requested name: text does not exist

[2021-07-15 20:35:20.499][57][serving][info][prediction_service.cpp:87] Getting modelInstance or pipeline failed. Model with requested name is not found

[2021-07-15 20:35:20.499][56][dag_executor][info][pipeline_factory.cpp:84] Pipeline with requested name: text does not exist

[2021-07-15 20:35:20.499][56][serving][info][prediction_service.cpp:87] Getting modelInstance or pipeline failed. Model with requested name is not found

[2021-07-15 20:35:20.522][58][dag_executor][info][pipeline_factory.cpp:84] Pipeline with requested name: text does not exist

[2021-07-15 20:35:20.522][58][serving][info][prediction_service.cpp:87] Getting modelInstance or pipeline failed. Model with requested name is not found

[2021-07-15 20:35:20.552][57][dag_executor][info][pipeline_factory.cpp:84] Pipeline with requested name: text does not exist

[2021-07-15 20:35:20.552][57][serving][info][prediction_service.cpp:87] Getting modelInstance or pipeline failed. Model with requested name is not found
```

And here is what the client says:
```
python camera_client.py --grpc_address localhost --grpc_port 9001         1m 11s
Initializing requesting thread index: 0
Initializing requesting thread index: 1
Initializing requesting thread index: 2
Initializing requesting thread index: 3
Launching requesting thread index: 0
Launching requesting thread index: 1
Launching requesting thread index: 2
Launching requesting thread index: 3
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "camera_client.py", line 115, in run
    result = stub.Predict(request, 10.0)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Model with requested name is not found"
	debug_error_string = "{"created":"@1626381320.476622000","description":"Error received from peer ipv6:[::1]:9001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Model with requested name is not found","grpc_status":5}"
>

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "camera_client.py", line 115, in run
    result = stub.Predict(request, 10.0)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Model with requested name is not found"
	debug_error_string = "{"created":"@1626381320.476595000","description":"Error received from peer ipv6:[::1]:9001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Model with requested name is not found","grpc_status":5}"
>

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "camera_client.py", line 115, in run
    result = stub.Predict(request, 10.0)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Model with requested name is not found"
	debug_error_string = "{"created":"@1626381320.498955000","description":"Error received from peer ipv6:[::1]:9001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Model with requested name is not found","grpc_status":5}"
>

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "camera_client.py", line 115, in run
    result = stub.Predict(request, 10.0)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/ryanloney/tmp/text-detection/text_env/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Model with requested name is not found"
	debug_error_string = "{"created":"@1626381320.529479000","description":"Error received from peer ipv6:[::1]:9001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Model with requested name is not found","grpc_status":5}"
>
```

**Comment by dkalinowski** [comment]
I have updated documentation with model name fix. It is already patched on branch and will be merged to develop today.

**Comment by dkalinowski** [comment]
Merged to develop now: https://github.com/openvinotoolkit/model_server/pull/773
