### ISSUE TITLE
ovms has a segment error when loading a shared library using the AVX512 instruction set using cpu_extension

### ISSUE THREAD

**Issue by zhaohb** [openvinotoolkit/model_server#842]
System information (version)

- OpenVINO => 2021.3
- Operating System / Platform => linux
- Compiler => gcc 8
- OpenVINO model server 2021.3 docker image

```shell
#./ovms --model_path /data/lat_open --model_name lat_open --port 9000 --cpu_extension /data/libextension.so --plugin_config '{"CPU_THROUGHPUT_STREAMS": "12"}' --shape auto
[2021-08-13 09:40:12.520][988][serving][info][server.cpp:105] OpenVINO Model Server 2021.3.c9ba5cfa
[2021-08-13 09:40:12.520][988][serving][info][server.cpp:106] OpenVINO backend 2021.3.394
[2021-08-13 09:40:12.520][988][serving][info][model.cpp:38] Getting model from /data/lat_open
[2021-08-13 09:40:12.520][988][serving][info][model.cpp:45] Model downloaded to /data/lat_open
[2021-08-13 09:40:12.520][988][serving][info][model.cpp:145] Will add model: lat_open; version: 1 ...
[2021-08-13 09:40:12.520][988][serving][info][modelinstance.cpp:495] Loading model: lat_open, version: 1, from path: /data/lat_open/1, with target device: CPU ...
[2021-08-13 09:40:12.520][988][serving][info][modelinstance.cpp:499] Some inputs shapes for model lat_open are set to auto
[2021-08-13 09:40:12.520][988][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model lat_open status change. New status: ( "state": "START", "error_code": "OK" )
[2021-08-13 09:40:12.520][988][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model lat_open status change. New status: ( "state": "LOADING", "error_code": "OK" )
[2021-08-13 09:40:12.521][988][serving][info][modelinstance.cpp:249] Loading custom CPU extension from /data/libextension.so
[2021-08-13 09:40:12.523][988][serving][info][modelinstance.cpp:252] Custom CPU extention loaded. Adding it.
Segmentation fault (core dumped)
```
if i do not avx512 instruction , it will be ok.

how to fix it, thank you very much.

**Comment by dtrawins** [comment]
@zhaohb on which CPU do you start OVMS? Does it support avx512 instructions? Can you share the extension code and the command for building it? We might need to reproduce it.

**Comment by zhaohb** [comment]
@dtrawins Yes, I think my CPU device supports AVX512. 

```shell
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz
Stepping:                        4
CPU MHz:                         1799.998
CPU max MHz:                     3000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4200.00
Virtualization:                  VT-x
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        24 MiB
L3 cache:                        33 MiB
NUMA node0 CPU(s):               0-11,24-35
NUMA node1 CPU(s):               12-23,36-47
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse
                                  sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl
                                 xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx1
                                 6 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand l
                                 ahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ib
                                 pb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erm
                                 s invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512
                                 bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm i
                                 da arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d
```

**Comment by zhaohb** [comment]
I had shared my code to you.

there are two folders in the custom_lib_error.tar.gz: custom_Layer and mnist_repo; custom_layer is the custom of  operator, custom_layer/build/libextension. so is the use of the operator avx512 library, custom_layer /no_avx512/ libextension.so is a shared library compiled without avX512. It is compiled in openvino centos7 2021.3 runtime image.

repeat the steps in Model Server2021.3:

> with avx512:

```shell
./ovms --model_path /data/mnist_repo/mnist --model_name mnist --port 9000 --cpu_extension /data/custom_layer/build/libextension.so --plugin_config '{"CPU_THROUGHPUT_STREAMS": "12"}' --shape auto
[2021-08-16 07:33:22.879][1709][serving][info][server.cpp:105] OpenVINO Model Server 2021.3.c9ba5cfa
[2021-08-16 07:33:22.879][1709][serving][info][server.cpp:106] OpenVINO backend 2021.3.394
[2021-08-16 07:33:22.879][1709][serving][info][model.cpp:38] Getting model from /data/mnist_repo/mnist
[2021-08-16 07:33:22.879][1709][serving][info][model.cpp:45] Model downloaded to /data/mnist_repo/mnist
[2021-08-16 07:33:22.879][1709][serving][info][model.cpp:145] Will add model: mnist; version: 1 ...
[2021-08-16 07:33:22.879][1709][serving][info][modelinstance.cpp:495] Loading model: mnist, version: 1, from path: /data/mnist_repo/mnist/1, with target device: CPU ...
[2021-08-16 07:33:22.879][1709][serving][info][modelinstance.cpp:499] Some inputs shapes for model mnist are set to auto
[2021-08-16 07:33:22.879][1709][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "START", "error_code": "OK" )
[2021-08-16 07:33:22.879][1709][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "LOADING", "error_code": "OK" )
[2021-08-16 07:33:22.880][1709][serving][info][modelinstance.cpp:249] Loading custom CPU extension from /data/custom_layer/build/libextension.so
[2021-08-16 07:33:22.883][1709][serving][info][modelinstance.cpp:252] Custom CPU extention loaded. Adding it.
Segmentation fault (core dumped)
```

> without avx512:

```shell
/ovms --model_path /data/mnist_repo/mnist --model_name mnist --port 9000 --cpu_extension /data/custom_layer/no_avx512/libextension.so --plugin_config '{"CPU_THROUGHPUT_STREAMS": "12"}' --shape auto
[2021-08-16 07:33:01.857][1646][serving][info][server.cpp:105] OpenVINO Model Server 2021.3.c9ba5cfa
[2021-08-16 07:33:01.858][1646][serving][info][server.cpp:106] OpenVINO backend 2021.3.394
[2021-08-16 07:33:01.858][1646][serving][info][model.cpp:38] Getting model from /data/mnist_repo/mnist
[2021-08-16 07:33:01.858][1646][serving][info][model.cpp:45] Model downloaded to /data/mnist_repo/mnist
[2021-08-16 07:33:01.858][1646][serving][info][model.cpp:145] Will add model: mnist; version: 1 ...
[2021-08-16 07:33:01.858][1646][serving][info][modelinstance.cpp:495] Loading model: mnist, version: 1, from path: /data/mnist_repo/mnist/1, with target device: CPU ...
[2021-08-16 07:33:01.858][1646][serving][info][modelinstance.cpp:499] Some inputs shapes for model mnist are set to auto
[2021-08-16 07:33:01.858][1646][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "START", "error_code": "OK" )
[2021-08-16 07:33:01.858][1646][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "LOADING", "error_code": "OK" )
[2021-08-16 07:33:01.858][1646][serving][info][modelinstance.cpp:249] Loading custom CPU extension from /data/custom_layer/no_avx512/libextension.so
[2021-08-16 07:33:01.860][1646][serving][info][modelinstance.cpp:252] Custom CPU extention loaded. Adding it.
[2021-08-16 07:33:01.861][1646][serving][info][modelinstance.cpp:254] Extention added.
[2021-08-16 07:33:01.866][1646][serving][info][modelinstance.cpp:126] Input name: Input3; mapping_name: ; shape: 1 1 28 28 ; precision: FP32, layout:NCHW
[2021-08-16 07:33:01.866][1646][serving][info][modelinstance.cpp:163] Output name: Plus214_Output_0 ; mapping name: ; shape: 1 10  ; precision: FP32, layout:NC
[2021-08-16 07:33:01.945][1646][serving][info][modelinstance.cpp:365] Plugin config for device CPU:
[2021-08-16 07:33:01.945][1646][serving][info][modelinstance.cpp:369] CPU_THROUGHPUT_STREAMS: 12
[2021-08-16 07:33:01.946][1646][serving][info][modelinstance.cpp:425] Loaded model mnist; version: 1; batch size: 1; No of InferRequests: 12
[2021-08-16 07:33:01.946][1646][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "AVAILABLE", "error_code": "OK" )
[2021-08-16 07:33:01.946][1646][serving][info][model.cpp:85] Updating default version for model: mnist, from: 0
[2021-08-16 07:33:01.946][1646][serving][info][model.cpp:95] Updated default version for model: mnist, to: 1
[2021-08-16 07:33:01.946][1701][modelmanager][info][modelmanager.cpp:639] Started model manager thread
[2021-08-16 07:33:01.946][1702][modelmanager][info][global_sequences_viewer.cpp:75] Started sequence cleaner thread
[2021-08-16 07:33:01.947][1646][serving][info][server.cpp:226] Server started on port 9000
```

**Comment by zhaohb** [comment]
@dtrawins can you reproduce the problem now？

**Comment by zhaohb** [comment]
@dtrawins can you test my code in model server ubuntu image? now I can not build ubuntu image success.

**Comment by atobiszei** [comment]
Hi @zhaohb,

There is probably something missing in package with instructions we received since I was unable to build library straight away:
{code}
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "Findngraph.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ngraph", but
  CMake did not find one.

  Could not find a package configuration file provided by "ngraph" with any
  of the following names:

    ngraphConfig.cmake
    ngraph-config.cmake
{code}

I checked tough both libraries and find that they were built using different compiler versions:
{code}
atobisze@mclx-23 10.91.242.161 [13:26:06] ~/custom_lib_error/custom_layer
strings build/libextension.so  | grep GCC
GCC_3.0
GCC: (GNU) 8.3.1 20190311 (Red Hat 8.3.1-3)
_Unwind_Resume@@GCC_3.0
atobisze@mclx-23 10.91.242.161 [13:26:50] ~/custom_lib_error/custom_layer
strings no_avx512/libextension.so | grep GCC
GCC_3.0
GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-44)
_Unwind_Resume@@GCC_3.0
{code}
Could you try switching gcc version?

**Comment by zhaohb** [comment]
yes，my share lib support avx512 is  build with  gcc 8.x version，because gcc4.x  does not support avx512.  so I must use gcc 8.x，so what can I do if I want use avx512？-------- 原始邮件 --------发件人： Adrian Tobiszewski ***@***.***>日期： 2021年8月18日周三 晚上7:46收件人： openvinotoolkit/model_server ***@***.***>抄送： zhaohb ***@***.***>, Mention ***@***.***>主    题： Re: [openvinotoolkit/model_server] ovms has a segment error when loading a shared library using the AVX512 instruction set using cpu_extension (#842)
Hi @zhaohb,
There is probably something missing in package with instructions we received since I was unable to build library straight away:
{code}
CMake Error at CMakeLists.txt:21 (find_package):
By not providing "Findngraph.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "ngraph", but
CMake did not find one.
Could not find a package configuration file provided by "ngraph" with any
of the following names:
ngraphConfig.cmake
ngraph-config.cmake

{code}
I checked tough both libraries and find that they were built using different compiler versions:
{code}
***@***.*** 10.91.242.161 [13:26:06] ~/custom_lib_error/custom_layer
strings build/libextension.so  | grep GCC
GCC_3.0
GCC: (GNU) 8.3.1 20190311 (Red Hat 8.3.1-3)
_Unwind_Resume@@GCC_3.0
***@***.*** 10.91.242.161 [13:26:50] ~/custom_lib_error/custom_layer
strings no_avx512/libextension.so | grep GCC
GCC_3.0
GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-44)
_Unwind_Resume@@GCC_3.0
{code}
Could you try switching gcc version?

**Comment by zhaohb** [comment]
@atobiszei sorry, the information was a little confusing, so let me rearrange it.
because the centos image version of GCC is 4.x, but 4.x does not support avx512 instruction, so I upgraded the GCC version to 8.x, so that the normal compilation can be done.

**Comment by zhaohb** [comment]
CMake Error at CMakeLists.txt:21 (find_package):
    By not providing "Findngraph.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "ngraph", but
    CMake did not find one.

    Could not find a package configuration file provided by "ngraph" with any
    of the following names:

    ngraphConfig.cmake
    ngraph-config.cmake

What is your build environment? which image is it compiled in?

**Comment by atobiszei** [comment]
With OVMS 2021.3 image i don't get the segfault just missing dependency:
```
docker run -v ~/models:/models -p 9171:9179 -e "http_proxy=$http_proxy"  -e "https_proxy=$https_proxy" --name zhaohb openvino/model_server:2021.3 --model_path /models/test/mnist_repo/mnist/ --model_name mnist --port 9000 --cpu_extension /models/test/custom_layer/build/l
ibextension.so --plugin_config '{"CPU_THROUGHPUT_STREAMS": "12"}' --shape auto

[2021-08-18 13:27:10.440][1][serving][info][server.cpp:105] OpenVINO Model Server 2021.3.c9ba5cfa
[2021-08-18 13:27:10.440][1][serving][info][server.cpp:106] OpenVINO backend 2021.3.394
[2021-08-18 13:27:10.440][1][serving][info][model.cpp:38] Getting model from /models/test/mnist_repo/mnist/
[2021-08-18 13:27:10.440][1][serving][info][model.cpp:45] Model downloaded to /models/test/mnist_repo/mnist/
[2021-08-18 13:27:10.440][1][serving][info][model.cpp:145] Will add model: mnist; version: 1 ...
[2021-08-18 13:27:10.440][1][serving][info][modelinstance.cpp:495] Loading model: mnist, version: 1, from path: /models/test/mnist_repo/mnist//1, with target device: CPU ...
[2021-08-18 13:27:10.440][1][serving][info][modelinstance.cpp:499] Some inputs shapes for model mnist are set to auto
[2021-08-18 13:27:10.440][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "START", "error_code": "OK" )
[2021-08-18 13:27:10.440][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "LOADING", "error_code": "OK" )
[2021-08-18 13:27:10.440][1][serving][info][modelinstance.cpp:249] Loading custom CPU extension from /models/test/custom_layer/build/libextension.so
[2021-08-18 13:27:10.440][1][serving][critical][modelinstance.cpp:256] Custom CPU extention loading has failed! Reason: Cannot load library '/models/test/custom_layer/build/libextension.so': libfarmhash.so.0: cannot open shared object file: No such file or directory
[2021-08-18 13:27:10.440][1][serving][error][modelinstance.cpp:483] exception occurred while loading network: Cannot load library '/models/test/custom_layer/build/libextension.so': libfarmhash.so.0: cannot open shared object file: No such file or directory
[2021-08-18 13:27:10.440][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "LOADING", "error_code": "UNKNOWN" )
[2021-08-18 13:27:10.440][1][serving][error][model.cpp:153] Error occurred while loading model: mnist; version: 1; error: Error while loading a network
[2021-08-18 13:27:10.440][1][modelmanager][error][modelmanager.cpp:850] Error occurred while loading model: mnist versions; error: Error while loading a network
[2021-08-18 13:27:10.441][1][modelmanager][error][modelmanager.cpp:73] Couldn't start model manager
[2021-08-18 13:27:10.441][1][serving][error][server.cpp:186] ovms::ModelManager::Start() Error: Error while loading a network
```

with `no_avx` ovms starts correctly.

**Comment by zhaohb** [comment]
```shell
docker run -v ~/models:/models -p 9171:9179 -e "http_proxy=$http_proxy"  -e "https_proxy=$https_proxy" --name zhaohb openvino/model_server:2021.3 --model_path /models/test/mnist_repo/mnist/ --model_name mnist --port 9000 --cpu_extension /models/test/custom_layer/build/l
ibextension.so --plugin_config '{"CPU_THROUGHPUT_STREAMS": "12"}' --shape auto

[2021-08-18 13:27:10.440][1][serving][info][server.cpp:105] OpenVINO Model Server 2021.3.c9ba5cfa
[2021-08-18 13:27:10.440][1][serving][info][server.cpp:106] OpenVINO backend 2021.3.394
[2021-08-18 13:27:10.440][1][serving][info][model.cpp:38] Getting model from /models/test/mnist_repo/mnist/
[2021-08-18 13:27:10.440][1][serving][info][model.cpp:45] Model downloaded to /models/test/mnist_repo/mnist/
[2021-08-18 13:27:10.440][1][serving][info][model.cpp:145] Will add model: mnist; version: 1 ...
[2021-08-18 13:27:10.440][1][serving][info][modelinstance.cpp:495] Loading model: mnist, version: 1, from path: /models/test/mnist_repo/mnist//1, with target device: CPU ...
[2021-08-18 13:27:10.440][1][serving][info][modelinstance.cpp:499] Some inputs shapes for model mnist are set to auto
[2021-08-18 13:27:10.440][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "START", "error_code": "OK" )
[2021-08-18 13:27:10.440][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "LOADING", "error_code": "OK" )
[2021-08-18 13:27:10.440][1][serving][info][modelinstance.cpp:249] Loading custom CPU extension from /models/test/custom_layer/build/libextension.so
[2021-08-18 13:27:10.440][1][serving][critical][modelinstance.cpp:256] Custom CPU extention loading has failed! Reason: Cannot load library '/models/test/custom_layer/build/libextension.so': libfarmhash.so.0: cannot open shared object file: No such file or directory
[2021-08-18 13:27:10.440][1][serving][error][modelinstance.cpp:483] exception occurred while loading network: Cannot load library '/models/test/custom_layer/build/libextension.so': libfarmhash.so.0: cannot open shared object file: No such file or directory
[2021-08-18 13:27:10.440][1][serving][info][modelversionstatus.hpp:155] STATUS CHANGE: Version 1 of model mnist status change. New status: ( "state": "LOADING", "error_code": "UNKNOWN" )
[2021-08-18 13:27:10.440][1][serving][error][model.cpp:153] Error occurred while loading model: mnist; version: 1; error: Error while loading a network
[2021-08-18 13:27:10.440][1][modelmanager][error][modelmanager.cpp:850] Error occurred while loading model: mnist versions; error: Error while loading a network
[2021-08-18 13:27:10.441][1][modelmanager][error][modelmanager.cpp:73] Couldn't start model manager
[2021-08-18 13:27:10.441][1][serving][error][server.cpp:186] ovms::ModelManager::Start() Error: Error while loading a network
```

there is no farmhash library in the system, you can install it.

**Comment by atobiszei** [comment]
Then there is issue with missing `libonnx_importer.so`. Do you have Dockerfile based on OVMS Dockerfile to share?

Please try building no_avx version of library with updated gcc (the same you used to compile one with AVX512). I suspect this is the issue.

**Comment by zhaohb** [comment]
libonnx_importer.so is located in the OVMS 2021.3 image /ovms/lib/libonnx_importer.so,  you can check whether there is libonnx_importer.so, this shared library is existing with OVMS image.

**Comment by zhaohb** [comment]
@atobiszei can you reproduce it now?

**Comment by atobiszei** [comment]
This is call stack from segfault

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f7eaddfdf33 in std::_Rb_tree<std::string, std::pair<std::string const, ngraph::DiscreteTypeInfo>, std::_Select1st<std::pair<std::string const, ngraph::DiscreteTypeInfo> >, std::less<std::string>, std::allocator<std::pair<std::string const, ngraph::DiscreteTypeInfo> > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, ngraph::DiscreteTypeInfo> >*) () from /ovms/lib/libinference_engine.so
Missing separate debuginfos, use: debuginfo-install glibc-2.17-317.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libuuid-2.23.2-65.el7.x86_64 libxml2-2.9.1-6.el7.5.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) info stack
#0  0x00007f7eaddfdf33 in std::_Rb_tree<std::string, std::pair<std::string const, ngraph::DiscreteTypeInfo>, std::_Select1st<std::pair<std::string const, ngraph::DiscreteTypeInfo> >, std::less<std::string>, std::allocator<std::pair<std::string const, ngraph::DiscreteTypeInfo> > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, ngraph::DiscreteTypeInfo> >*) () from /ovms/lib/libinference_engine.so
#1  0x00007f7ead0fe47b in ngraph::OpSet::~OpSet() () from /ovms/lib/libngraph.so
#2  0x00007f7e9647df89 in DeepfmExtension::Extension::getOpSets() () from /models/test/custom_layer/build/libextension.so
#3  0x00007f7eade3e8e2 in InferenceEngine::Extension::getOpSets() () from /ovms/lib/libinference_engine.so
#4  0x00007f7eade24a69 in ?? () from /ovms/lib/libinference_engine.so
#5  0x00007f7eade24f9c in InferenceEngine::Core::AddExtension(std::shared_ptr<InferenceEngine::IExtension>, std::string const&) () from /ovms/lib/libinference_engine.so
#6  0x000055b5d3b44c76 in ovms::ModelInstance::loadOVEngine() ()
#7  0x000055b5d3b4aa58 in ovms::ModelInstance::loadModelImpl(ovms::ModelConfig const&, ovms::DynamicModelParameter const&) ()
#8  0x000055b5d3b4affc in ovms::ModelInstance::loadModel(ovms::ModelConfig const&) ()
#9  0x000055b5d3beb9c9 in ovms::Model::addVersion(ovms::ModelConfig const&) ()
#10 0x000055b5d3bed563 in ovms::Model::addVersions(std::shared_ptr<std::vector<long, std::allocator<long> > >, ovms::ModelConfig&, std::shared_ptr<ovms::FileSystem>&, std::shared_ptr<std::vector<long, std::allocator<long> > >) ()
#11 0x000055b5d3b21550 in ovms::ModelManager::addModelVersions(std::shared_ptr<ovms::Model>&, std::shared_ptr<ovms::FileSystem>&, ovms::ModelConfig&, std::shared_ptr<std::vector<long, std::allocator<long> > >&, std::shared_ptr<std::vector<long, std::allocator<long> > >) ()
#12 0x000055b5d3b2411f in ovms::ModelManager::reloadModelWithVersions(ovms::ModelConfig&) ()
#13 0x000055b5d3b26f13 in ovms::ModelManager::startFromConfig() ()
#14 0x000055b5d3b2d7de in ovms::ModelManager::start() ()
#15 0x000055b5d3af445b in startGRPCServer(ovms::PredictionServiceImpl&, ovms::ModelServiceImpl&) ()
#16 0x000055b5d3af5105 in server_main(int, char**) ()
#17 0x00007f7eab5f7555 in __libc_start_main () from /lib64/libc.so.6
#18 0x000055b5d3ac4ecf in _start () 
```

@zhaohb 
Did you try to load extension library with no_avx support built with GCC 8.3.1 (same as avx version)?
Did you try to load those libraries in application with OpenVINO but without OVMS?

**Comment by zhaohb** [comment]
@atobiszei  oh, sorry, I just tried to compile the without avx512 instruction code using GCC 8.3, and still reported a segment error when loading using ovms. It seems that the segment error is not caused by the instruction, is it caused by the upgraded GCC version?
I used the openvino/ubuntu_dev image to load the shared library with the instruction, it is ok, but I also compile the shared library in the openVino/ubuntu_dev image.

**Comment by zhaohb** [comment]
@atobiszei can you test it in ovms ubuntu image? maybe it will be solved.  because I cannot successfully build  ovms
 ubuntu image, so I do not test it.

**Comment by atobiszei** [comment]
I tried to test on OVMS Ubuntu build image but with no success:
```
[2021-08-19 12:35:51.627][61985][serving][critical][modelinstance.cpp:288] Custom CPU extention loading has failed! Reason: Cannot load library '/models/test/custom_layer/no_avx512/libextension.so': /models/test/custom_layer/no_avx512/libextension.so: undefined symbol: _ZNK6ngraph4Node11descriptionEv
[2021-08-19 12:35:51.627][61985][serving][error][modelinstance.cpp:514] exception occurred while loading network: Cannot load library '/models/test/custom_layer/no_avx512/libextension.so': /models/test/custom_layer/no_avx512/libextension.so: undefined symbol: _ZNK6ngraph4Node11descriptionEv
```

But it is I would say expected due to incompatibility between library built on CentOS vs Ubuntu. I tried to built this library in Ubuntu image but I have error mentioned above (cmake having issue with finding ngraph) -> that's why either Ubuntu Dockerfile or steps to setup system for building this library would be required for Ubuntu.

You could also check our Ubuntu image on develop branch but as mentioned in https://github.com/openvinotoolkit/model_server/issues/846
this will be officially released in ~2weeks time.

**Comment by zhaohb** [comment]
@atobiszei in ubuntu ovms image you should recompile the shared library, you can use openvino/ubuntu_dev:2021.4 image to compile code. 
my share library was compiled in centos7 image, so can not load.

**Comment by zhaohb** [comment]
@atobiszei Can you share the ubuntu OVMS image with me? then I can also test it.

**Comment by atobiszei** [comment]
Unfortunately I cannot share our internal images, just instruction to recreate one.

This is the name locally created image:
`OVMS_ubuntu_develop-build`
after running such command on develop branch:
```BASE_OS=ubuntu no_proxy=localhost,127.0.0.1 OVMS_CPP_DOCKER_IMAGE=OVMS_ubuntu_develop JOBS=24 make docker_build```

I get:
```
docker pull openvino/ubuntu_dev:2021.4
Error response from daemon: pull access denied for openvino/ubuntu_dev
```
Is this the same as:
docker pull openvino/ubuntu20_dev?

**Comment by zhaohb** [comment]
I think it should be openvino/ubuntu20_dev:2021.4

**Comment by zhaohb** [comment]
@atobiszei I build ubuntu image, and it had solved my question, thank you very much.
