### ISSUE TITLE
file_line":1069,"grpc_message":"Missing input with specific name - Required input: 0","grpc_status":3}"

### ISSUE THREAD

**Issue by lamalexck** [openvinotoolkit/model_server#874]
I was able to run get_serving_meta and verify my model is in place.
But, when I tried to run inference, it failed with missing input with specific name.
Both jpeg_classification and grpc_serving_client failed.

(venv-ovms-client) wlc@cloudimg-clusteradmin:~/projects/model_server/example_client$ **python3 get_serving_meta.py --grpc_address $NODE --grpc_port $NODEPORT --model_name resnet50-binary-0001**
2021-08-24 00:10:44.207933: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-24 00:10:44.207985: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Getting model metadata for model: resnet50-binary-0001
Inputs metadata:
	Input name: 0; shape: [16, 3, 224, 224]; dtype: DT_FLOAT
Outputs metadata:
	Output name: 1463; shape: [16, 1000]; dtype: DT_FLOAT

(venv-ovms-client) wlc@cloudimg-clusteradmin:~/projects/model_server/example_client$ **python3 jpeg_classification.py --grpc_address $NODE --grpc_port $NODEPORT --input_name data --output_name prob --model_name resnet50-binary-0001 --images_list input_images.txt**
2021-08-24 00:08:36.897766: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-24 00:08:36.897905: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Start processing:
	Model name: resnet50-binary-0001
	Images list file: input_images.txt
images/airliner.jpeg (1, 3, 224, 224) ; data range: 0.0 : 255.0
Traceback (most recent call last):
  File "jpeg_classification.py", line 95, in <module>
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
  File "/home/wlc/projects/model_server/example_client/venv-ovms-client/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/wlc/projects/model_server/example_client/venv-ovms-client/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Missing input with specific name - Required input: 0"
	debug_error_string = "{"created":"@1629763717.782239872","description":"Error received from peer ipv4:192.168.100.196:31056","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Missing input with specific name - Required input: 0","grpc_status":3}"

(venv-ovms-client) wlc@cloudimg-clusteradmin:~/projects/model_server/example_client$ **python3 grpc_serving_client.py --grpc_address $NODE --grpc_port $NODEPORT --model_name resnet50-binary-0001 --images_numpy_path imgs.npy --input_name data --output_name prob --transpose_input False --labels_numpy_path lbs.npy**
2021-08-24 00:16:02.717769: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-24 00:16:02.717805: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Image data range: 0.0 : 255.0
Start processing:
	Model name: resnet50-binary-0001
	Iterations: 10
	Images numpy path: imgs.npy
	Images in shape: (10, 3, 224, 224)

Traceback (most recent call last):
  File "grpc_serving_client.py", line 130, in <module>
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
  File "/home/wlc/projects/model_server/example_client/venv-ovms-client/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/wlc/projects/model_server/example_client/venv-ovms-client/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Missing input with specific name - Required input: 0"
	debug_error_string = "{"created":"@1629764163.640239762","description":"Error received from peer ipv4:192.168.100.196:31056","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Missing input with specific name - Required input: 0","grpc_status":3}"

**Comment by mzegla** [comment]
The problem is with the part `--input_name data --output_name prob` of inference scripts. Those values do not match the names of input and output of your model. You can read inputs and outputs names from model metadata call:

> Getting model metadata for model: resnet50-binary-0001
> Inputs metadata:
> Input name: **0**; shape: [16, 3, 224, 224]; dtype: DT_FLOAT
> Outputs metadata:
> Output name: **1463**; shape: [16, 1000]; dtype: DT_FLOAT

So you'd need to modify your commands to contain  `--input_name 0 --output_name 1463` and it should work.
