### ISSUE TITLE
File "grpc_serving_client.py", line 130, in <module>     result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs

### ISSUE THREAD

**Issue by wh28533** [openvinotoolkit/model_server#890]
root@hayoung-desktop:/models# **python3 grpc_serving_client.py --grpc_port 9000 --images_numpy_path imgs.npy --input_name data --output_name prob --transpose_input False --labels_numpy_path lbs.npy**
2021-08-30 07:06:44.855094: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino/opencv/lib:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib::/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/omp/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64
2021-08-30 07:06:44.855117: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Image data range: 0.0 : 255.0
Start processing:
	Model name: resnet
	Iterations: 10
	Images numpy path: imgs.npy
	Numpy file shape: (10, 3, 224, 224)

Traceback (most recent call last):
  File "grpc_serving_client.py", line 130, in <module>
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Missing input with specific name - Required input: map/TensorArrayStack/TensorArrayGatherV3"
	debug_error_string = "{"created":"@1630307205.766426264","description":"Error received from peer ipv6:[::1]:9000","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Missing input with specific name - Required input: map/TensorArrayStack/TensorArrayGatherV3","grpc_status":3}"
>

**Comment by wh28533** [comment]
oh, I got it. 
That's input/output name need to change using grpc_serving_meta.py.

Thank you.
